services:

  Telegram_file_uploader:
    # build: .
    image: j0n4n/telegram_file_uploader:latest
    container_name: Telegram_file_uploader
    environment:
      TG_API_ID: 
      TG_API_HASH: 
      TG_BOT_TOKEN: 
      TG_AUTHORIZED_USERS_ID: 
      # TG_SESSION: # OPTIONAL
      # BOT_UPLOAD_DIR: # OPTIONAL
      # BOT_UPDATE_UPLOAD_INTERVAL: # OPTIONAL
      # SEND_PUBLIC_IP: # OPTIONAL
      # SEND_VIDEO_INFO: # OPTIONAL
      # LANGUAGE_VIDEO_INFO: # OPTIONAL
    volumes:
      - ./sendFiles:/sendFiles
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8g"